<?php


namespace ivoglent\yii2\apm\listeners;


use ivoglent\yii2\apm\Listener;
use yii\base\ActionEvent;
use yii\base\Event;
use yii\console\Application;

class WorkerListener extends Listener
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        Event::on(Application::class, Application::EVENT_BEFORE_ACTION, [$this, 'beforeExecute']);
        Event::on(Application::class, Application::EVENT_AFTER_ACTION, [$this, 'afterExecute']);
    }

    /**
     * @param Event $event
     */
    public function beforeExecute(Event $event) {
        $sender = $event->sender;
        if ($sender instanceof WorkerInterface) {
            $txtName = $sender->getName();
            \Yii::info('Worker start: ' . $txtName, 'apm');
            $this->agent->startTransaction($txtName, 'worker');
        }
    }

    /**
     * @param ActionEvent $event
     * @throws \Elastic\Apm\PhpAgent\Exception\RuntimeException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function afterAction(ActionEvent $event) {
        $sender = $event->sender;
        if ($sender instanceof WorkerInterface) {
            $result = $sender->getResult();
            \Yii::info('Worker stop: ' . $txtName, 'apm');
            $this->agent->stopTransaction($result);
        }
    }
}