<?php


namespace ivoglent\yii2\apm;

use Elastic\Apm\PhpAgent\Agent as BaseAgent;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;

class Agent extends BaseAgent
{
    public $transactionStarted = false;

    public function startTransaction(string $name, string $type, ?string $id = null)
    {
        parent::startTransaction($name, $type, $id); // TODO: Change the autogenerated stub
        $this->transactionStarted = true;
    }

    public function stopTransaction(?string $result = null): void
    {
        parent::stopTransaction($result); // TODO: Change the autogenerated stub
        $this->transactionStarted = false;
    }

    /*public function send(?RequestInterface $request = null): bool
    {
        $request = $this->makeRequest();
        $logs = (sprintf('Sending data %s to endpoint %s', $request->getBody()->getContents(), $request->getUri()));
        \Yii::info($logs, 'apm');
        try {
            return parent::send($request);
        } catch (\Exception $e) {
            \Yii::error($e);
        }
        return false;
    }*/
}